/* Data store keys or key prefixes */

export const FIRST_DATA_TS_IS_KEY = 'FIRST_DATA_TIMESTAMP';

export const INITIAL_INDEXES_IS_KEY = 'INITIAL_INDEXES';
export const TOTAL_COSTS_IS_KEY = 'TOTAL_COSTS';
export const TOTAL_SUPPLIED_IS_KEY = 'TOTAL_SUPPLIED';

export const PER_DAY_INDEXES_IS_KEY_PREFIX = 'DAY_INDEXES_';
export const PER_DAY_COSTS_IS_KEY_PREFIX = 'DAY_COSTS_';
export const PER_DAY_SUPPLIED_IS_KEY_PREFIX = 'DAY_SUPPLIED_';
